[package]
name = "serde_hkx_hkanno"
version = "0.1.0"
description = "Serde serialization for hkanno annotation tracks"

authors.workspace = true
categories = []
edition.workspace = true
keywords = []
license = ""
readme = "../../README.md"
repository.workspace = true
rust-version.workspace = true

[dependencies]
winnow = "0.7.14"
rayon = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

havok_classes = { workspace = true }
havok_types = { workspace = true }
serde_hkx_features = { workspace = true }
