//! Update HKX / XML files using annotation (.txt) files.
//!
//! ## Overview
//! This module updates HKX (and compatible XML) files by applying annotations
//! generated by the `dump` command.
//!
//! The behavior is fully driven by the combination of:
//! - input (`--input`): file or directory
//! - annotation source (`--anno`): file, directory, or omitted
//! - output (`--output`): file, directory, or omitted
//!
//! Annotations are matched by **file stem** when a directory is used.
//!
//! ---
//!
//! ## Example Directory Layout
//!
//! ```text
//! .
//! ├── hkxc-anno-annos
//! │   ├── paired_1hmkillmovebackstab.txt
//! │   └── paired_1hmkillmovec.txt
//! ├── hkxc.exe
//! └── tests
//!     ├── paired_1hmkillmovebackstab.hkx
//!     └── paired_1hmkillmovec.xml
//! ```
//!
//! ---
//!
//! ## Annotation Resolution Rules
//!
//! ### `--anno` omitted
//! - Uses the default annotation directory: `hkxc-anno-annos/`
//! - For each input file, the annotation file is resolved as:
//!
//! ```text
//! hkxc-anno-annos/<input_file_stem>.txt
//! ```
//!
//! Example:
//!
//! ```text
//! tests/paired_1hmkillmovebackstab.hkx
//!   → hkxc-anno-annos/paired_1hmkillmovebackstab.txt
//! ```
//!
//! ---
//!
//! ### `--anno <file>`
//! - The specified annotation file is applied to:
//!   - the single input file, or
//!   - **all files** when the input is a directory
//!
//! This forces the same annotation onto every processed file.
//!
//! ---
//!
//! ### `--anno <directory>`
//! - The directory is treated as an annotation folder
//! - For each input file, a matching `.txt` file is searched by stem
//!
//! ```text
//! <anno_dir>/<input_file_stem>.txt
//! ```
//!
//! ---
//!
//! ## Input Rules
//!
//! ### Input is a file
//! - Exactly one file is updated
//! - The corresponding annotation is resolved according to the rules above
//!
//! ### Input is a directory
//! - All supported files in the directory are processed
//! - Each file resolves its annotation independently
//!
//! ---
//!
//! ## Output Rules
//!
//! ### `--output` omitted
//! - The input file(s) are **overwritten in place**
//!
//! ### `--output <directory>`
//! - Updated files are written into the directory
//! - File names are preserved
//! - The input directory is left unchanged

/// Representation command examples.
pub const EXAMPLES: &str = r#"EXAMPLES:
- Update a single HKX file in place (default annotation folder, keep format)
  hkxc anno-update -i paired_1hmkillmovebackstab.hkx

- Update all HKX/XML files in a directory in place
  hkxc anno-update -i tests/

- Use a specific annotation file for a single input
  hkxc anno-update -i paired_1hmkillmovebackstab.hkx -a paired_1hmkillmovebackstab.txt

- Apply one annotation file to all files in the input directory
  hkxc anno-update -i tests/ -a common.txt

- Use a custom annotation directory instead of the default
  hkxc anno-update -i tests/ -a my-anno-dir/

- Write updated files to a separate output directory (keep original format)
  hkxc anno-update -i tests/ -o out/

- Write updated file to a different path (keep original format)
  hkxc anno-update -i paired_1hmkillmovebackstab.hkx -o out/paired_1hmkillmovebackstab.hkx

- Convert output format explicitly while writing to a new location
  hkxc anno-update -i paired_1hmkillmovebackstab.hkx -o out/paired_1hmkillmovebackstab.hkx -v win32

- Convert all files in a directory to a specific format
  hkxc anno-update -i tests/ -o out/ -v amd64


INVALID PATTERNS:
- Missing required input
  hkxc anno-update

- Annotation specified without input
  hkxc anno-update -a anno.txt

- Input directory with output file path
  hkxc anno-update -i tests/ -o out/file.hkx

- Non-existent annotation directory
  hkxc anno-update -i tests/ -a does-not-exist/
"#;

use serde_hkx_features::{fs::ReadExt as _, progress::ProgressHandler, Format};
use std::path::{Path, PathBuf};

#[derive(Debug, clap::Args)]
#[clap(arg_required_else_help = true, after_long_help = EXAMPLES)]
pub(crate) struct UpdateArgs {
    /// Input HKX file or directory to update
    #[arg(short = 'i', long = "input")]
    input: PathBuf,

    /// Annotation source: file or directory. default: `hkxc-anno-annos` dir.
    #[arg(short = 'a', long = "anno")]
    anno: Option<PathBuf>,

    /// Output path for updated files. If omitted, updates in place.
    #[arg(short = 'o', long = "output")]
    output: Option<PathBuf>,

    /// Force output format. If omitted, keeps the input format.
    #[arg(short = 'v', long = "format")]
    format: Option<Format>,
}

pub(crate) async fn update(args: &UpdateArgs) -> Result<(), crate::args::AnyError> {
    let anno_base = args
        .anno
        .as_deref()
        .unwrap_or_else(|| Path::new("hkxc-anno-annos"));

    let output = args.output.as_deref();

    if args.input.is_file() {
        update_file(&args.input, anno_base, output, args.format).await?;
    } else if args.input.is_dir() {
        update_dir(
            &args.input,
            anno_base,
            output,
            args.format,
            crate::args::progress_handler::CliProgressHandler::new(),
        )
        .await?;
    } else {
        return Err(format!(
            "Expected a directory or file, but this path is neither.: {}",
            args.input.display()
        )
        .into());
    }

    Ok(())
}

async fn update_file(
    input: &Path,
    anno_base: &Path,
    output: Option<&Path>,
    forced_format: Option<Format>,
) -> Result<(), crate::args::AnyError> {
    let anno_path = resolve_anno_path(input, anno_base)
        .ok_or_else(|| format!("annotation not found for input: {}", input.display()))?;

    let hkanno_str = anno_path.read_any_string().await?;
    let mut bytes = input.read_bytes().await?;

    let out_format = decide_output_format(input, forced_format)?;
    let updated = serde_hkx_hkanno::parse_hkanno_str(&hkanno_str)?
        .update_hkx_bytes(&mut bytes, out_format, input)?;

    let mut out = output.unwrap_or(input).to_path_buf();
    if forced_format.is_some() {
        out.set_extension(out_format.as_extension());
    }

    if let Some(parent) = out.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }

    tokio::fs::write(out, updated).await?;
    Ok(())
}

async fn update_dir<P>(
    input_dir: &Path,
    anno_base: &Path,
    output: Option<&Path>,
    forced_format: Option<Format>,
    mut progress_handler: P,
) -> Result<(), crate::args::AnyError>
where
    P: ProgressHandler + Send + Sync + Clone + 'static,
{
    let mut targets = Vec::new();
    let mut rd = tokio::fs::read_dir(input_dir).await?;

    while let Some(entry) = rd.next_entry().await? {
        let input = entry.path();

        let Some(ext) = input.extension() else {
            return Ok(());
        };
        if Format::from_extension(ext).is_err() {
            continue;
        }

        match resolve_anno_path(&input, anno_base) {
            Some(anno_path) => {
                targets.push((input, anno_path));
            }
            None => {
                tracing::info!(
                    path = %input.display(),
                    anno_base = %anno_base.display(),
                    "Skipping file: corresponding annotation not found"
                );
            }
        }
    }

    if targets.is_empty() {
        progress_handler.on_empty();
        return Ok(());
    }

    progress_handler.on_set_total(targets.len());

    if let Some(dir) = output {
        tokio::fs::create_dir_all(dir).await?;
    }

    let mut handles = tokio::task::JoinSet::new();

    for (input, anno_path) in targets {
        let output = output.map(Path::to_path_buf);
        let forced_format = forced_format;

        let progress_handler = progress_handler.clone();
        handles.spawn(async move {
            let result = async {
                let hkanno_str = anno_path.read_any_string().await?;
                let mut bytes = input.read_bytes().await?;

                let out_format = decide_output_format(&input, forced_format)?;
                let updated = serde_hkx_hkanno::parse_hkanno_str(&hkanno_str)?
                    .update_hkx_bytes(&mut bytes, out_format, &input)?;

                let mut out = match &output {
                    Some(dir) => dir.join(input.file_name().unwrap()),
                    None => input.clone(),
                };

                if forced_format.is_some() {
                    out.set_extension(out_format.as_extension());
                }

                if let Some(parent) = out.parent() {
                    tokio::fs::create_dir_all(parent).await?;
                }

                tokio::fs::write(out, updated).await?;
                progress_handler.inc(1);
                Ok::<_, crate::args::AnyError>(())
            }
            .await;

            (input, result)
        });
    }

    while let Some(joined) = handles.join_next().await {
        match joined {
            Ok((input, Ok(()))) => {
                progress_handler.on_processing_path(&input);
                progress_handler.success_inc(1);
            }
            Ok((input, Err(e))) => {
                progress_handler.on_processing_path(&input);
                progress_handler.failure_inc(1);
                tracing::error!(
                    error = %e,
                    path = %input.display(),
                    "Failed to update file"
                );
            }
            Err(e) => {
                progress_handler.failure_inc(1);
                tracing::error!(
                    error = %e,
                    "Join error in update task"
                );
            }
        }

        progress_handler.inc(1);
    }

    progress_handler.on_finish();
    Ok(())
}

/// Returns annotation txt path.
fn resolve_anno_path(input: &Path, anno_base: &Path) -> Option<PathBuf> {
    if anno_base.is_file() {
        return Some(anno_base.to_path_buf());
    }

    let stem = input.file_stem()?;
    let path = anno_base.join(stem).with_extension("txt");
    path.exists().then_some(path)
}

fn decide_output_format(
    input: &Path,
    forced: Option<Format>,
) -> Result<Format, crate::args::AnyError> {
    Ok(match forced {
        Some(f) => f,
        None => Format::from_current_format(input)?,
    })
}
