//! Update HKX / XML files using annotation (.txt) files.
//!
//! ## Overview
//! This module updates HKX (and compatible XML) files by applying annotations
//! generated by the `dump` command.
//!
//! The behavior is fully driven by the combination of:
//! - input (`--input`): file or directory
//! - annotation source (`--anno`): file, directory, or omitted
//! - output (`--output`): file, directory, or omitted
//!
//! Annotations are matched by **file stem** when a directory is used.
//!
//! ---
//!
//! ## Example Directory Layout
//!
//! ```text
//! .
//! ├── hkxc-anno-annos
//! │   ├── paired_1hmkillmovebackstab.txt
//! │   └── paired_1hmkillmovec.txt
//! ├── hkxc.exe
//! └── tests
//!     ├── paired_1hmkillmovebackstab.hkx
//!     └── paired_1hmkillmovec.xml
//! ```
//!
//! ---
//!
//! ## Annotation Resolution Rules
//!
//! ### `--anno` omitted
//! - Uses the default annotation directory: `hkxc-anno-annos/`
//! - For each input file, the annotation file is resolved as:
//!
//! ```text
//! hkxc-anno-annos/<input_file_stem>.txt
//! ```
//!
//! Example:
//!
//! ```text
//! tests/paired_1hmkillmovebackstab.hkx
//!   → hkxc-anno-annos/paired_1hmkillmovebackstab.txt
//! ```
//!
//! ---
//!
//! ### `--anno <file>`
//! - The specified annotation file is applied to:
//!   - the single input file, or
//!   - **all files** when the input is a directory
//!
//! This forces the same annotation onto every processed file.
//!
//! ---
//!
//! ### `--anno <directory>`
//! - The directory is treated as an annotation folder
//! - For each input file, a matching `.txt` file is searched by stem
//!
//! ```text
//! <anno_dir>/<input_file_stem>.txt
//! ```
//!
//! ---
//!
//! ## Input Rules
//!
//! ### Input is a file
//! - Exactly one file is updated
//! - The corresponding annotation is resolved according to the rules above
//!
//! ### Input is a directory
//! - All supported files in the directory are processed
//! - Each file resolves its annotation independently
//!
//! ---
//!
//! ## Output Rules
//!
//! ### `--output` omitted
//! - The input file(s) are **overwritten in place**
//!
//! ### `--output <directory>`
//! - Updated files are written into the directory
//! - File names are preserved
//! - The input directory is left unchanged
use serde_hkx_features::{fs::ReadExt as _, progress::ProgressHandler};
use std::path::{Path, PathBuf};

#[derive(Debug, clap::Args)]
#[clap(arg_required_else_help = true)]
pub(crate) struct UpdateArgs {
    /// Annotation source: can be a file or directory. If a file: applies to single input or all files in input directory. If a directory: uses it as the annotation folder to find matching .txt files. If omitted: uses default hkxc-anno-annos folder.
    #[arg(short = 'a', long = "anno")]
    anno: Option<PathBuf>,

    /// Input HKX file or directory containing HKX files to update
    #[arg(short = 'i', long = "input")]
    input: PathBuf,

    /// Output path for updated HKX files. If omitted, overwrites the input files.
    #[arg(short = 'o', long = "output")]
    output: Option<PathBuf>,

    /// Output format: 'amd64' for 64-bit Skyrim SE/AE, 'win32' for 32-bit Skyrim LE
    #[arg(short = 'v', long = "format")]
    format: serde_hkx_features::OutFormat,
}

pub(crate) async fn update(args: &UpdateArgs) -> Result<(), crate::args::AnyError> {
    // Annotation file or dir
    let anno_base = match args.anno.as_ref() {
        Some(p) => p,
        None => Path::new("hkxc-anno-annos"),
    };

    let output = args.output.as_deref();
    if args.input.is_file() {
        update_file(&args.input, anno_base, output, args.format).await?;
    } else if args.input.is_dir() {
        update_dir(
            &args.input,
            anno_base,
            output,
            args.format,
            crate::args::progress_handler::CliProgressHandler::new(),
        )
        .await?;
    }

    Ok(())
}

async fn update_file(
    input: &Path,
    anno_base: &Path,
    output: Option<&Path>,
    format: serde_hkx_features::OutFormat,
) -> Result<(), crate::args::AnyError> {
    let hkanno_str = load_hkanno_str(input, anno_base).await?;
    let mut bytes = input.read_bytes().await?;

    let updated = serde_hkx_hkanno::parse_hkanno_str(&hkanno_str)?
        .update_hkx_bytes(&mut bytes, format, input)?;

    let out = output.unwrap_or(input);
    tokio::fs::write(out, updated).await?;

    Ok(())
}

async fn update_dir(
    input_dir: &Path,
    anno_base: &Path,
    output: Option<&Path>,
    format: serde_hkx_features::OutFormat,
    mut progress_handler: impl ProgressHandler,
) -> Result<(), crate::args::AnyError> {
    // collect valid inputs
    let mut targets = Vec::new();
    let mut rd = tokio::fs::read_dir(input_dir).await?;
    while let Some(entry) = rd.next_entry().await? {
        let input = entry.path();

        if let Err(e) = serde_hkx_hkanno::OutFormat::from_input(&input) {
            tracing::info!(
                path = %input.display(),
                "Skipping file: {e}"
            );
            continue;
        }

        let anno_path = {
            let input: &Path = &input;
            if anno_base.is_file() {
                Some(anno_base.to_path_buf());
            }

            input.file_stem().and_then(|stem| {
                let path = anno_base.join(stem).with_extension("txt");
                tracing::debug!(calculated_annotation_path = %path.display());
                path.exists().then_some(path)
            })
        };

        match anno_path {
            Some(anno_path) => {
                targets.push((input, anno_path));
            }
            None => {
                tracing::info!(
                    path = %input.display(),
                    anno_base = %anno_base.display(),
                    "Skipping file: corresponding annotation not found"
                );
            }
        }
    }

    if targets.is_empty() {
        progress_handler.on_empty();
        return Ok(());
    }

    progress_handler.on_set_total(targets.len());

    // output dir create once
    if let Some(dir) = output {
        tokio::fs::create_dir_all(dir).await?;
    }

    let mut handles = tokio::task::JoinSet::new();

    for (input, anno_path) in targets {
        let output = output.map(Path::to_path_buf);

        handles.spawn(async move {
            let result = async {
                let hkanno_str = anno_path.read_any_string().await?;
                let mut bytes = input.read_bytes().await?;

                let updated = serde_hkx_hkanno::parse_hkanno_str(&hkanno_str)?
                    .update_hkx_bytes(&mut bytes, format, &input)?;

                let out = match &output {
                    Some(dir) => dir.join(input.file_name().unwrap()),
                    None => input.clone(),
                };

                if let Some(parent) = out.parent() {
                    tokio::fs::create_dir_all(parent).await?;
                }

                tokio::fs::write(out, updated).await?;
                Ok::<_, crate::args::AnyError>(())
            }
            .await;

            (input, result)
        });
    }

    while let Some(joined) = handles.join_next().await {
        match joined {
            Ok((input, Ok(()))) => {
                progress_handler.on_processing_path(&input);
                progress_handler.success_inc(1);
            }
            Ok((input, Err(e))) => {
                progress_handler.on_processing_path(&input);
                progress_handler.failure_inc(1);
                tracing::error!(
                    error = %e,
                    path = %input.display(),
                    "Failed to update file"
                );
            }
            Err(e) => {
                progress_handler.failure_inc(1);
                tracing::error!(
                    error = %e,
                    "Join error in update task"
                );
            }
        }

        progress_handler.inc(1);
    }

    progress_handler.on_finish();
    Ok(())
}

async fn load_hkanno_str(input: &Path, anno_base: &Path) -> Result<String, crate::args::AnyError> {
    if anno_base.is_file() {
        return Ok(anno_base.read_any_string().await?);
    }

    let stem = input
        .file_stem()
        .ok_or_else(|| format!("invalid input file: {}", input.display()))?;

    let anno_path = anno_base.join(stem).with_extension("txt");
    Ok(anno_path.read_any_string().await?)
}
